services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build: .
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      YC_API_KEY: ""
      YC_FOLDER_ID: ""

volumes:
  qdrant_data:
